#!/usr/bin/env python
import sqlite3

conn = sqlite3.connect('database.db')
c = conn.cursor()

print('Content-type: text/html')
print()
print('<!DOCTYPE html>')
print('<html lang="en">')
print('<head>')
print('	<title>Database</title>')
print('	<meta charset="utf-8">')
print('	<meta name="viewport" content="width=device-width, initial-scale=1">')
print('	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">')
print('	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>')
print('	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>')
print('</head>')
print('<body>')
print('<div class="container">')
print('	<div class="jumbotron">')
print('		<h1>Database</h1>')
print('	</div>')
print('	<table class="table table-hover">')
print('		<thead>')
print('			<tr>')
print('				<th>Name</th>')
print('				<th>Size</th>')
print('				<th>Price</th>')
print('				<th>Source</th>')
print('			</tr>')
print('		</thead>')
print('		<tbody>')

for row in c.execute('SELECT * FROM ingredients'):
	print('			<tr>')
	print('				<td>%s</td>' % (row[0]))
	print('				<td>%i%s</td>' % (row[1], row[2]))
	print('				<td>$%.2f</td>' % (row[3]))
	print('				<td><a href="%s">%s</a></td>' % (row[4], row[5]))
	print('			</tr>')

print('		</tbody>')
print('	</table>')
print('	<div class="row">')
print('		<footer style="text-align: center">')
print('			<p>Copyright 2015 Justin Willis</p>')
print('			<a href="https://github.com/bkvaluemeal/north-american-wookie" class="btn btn-link" role="button">GitHub</a>')
print('		</footer>')
print('	</div>')
print('</div>')
print('</body>')
print('</html>')
